version: "3.8"

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ../Backend
      dockerfile: ../Docker/Dockerfile.backend
    container_name: docker-backend
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      - app-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EmployeeDB;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False

networks:
  app-network:
    driver: bridge
